name: 'Random Word Generator'
description: 'Generate a string of random english words'
author: 'acyphus'
branding:
  icon: 'book-open'
  color: 'blue'

# Define your inputs here.
inputs:
  number-of-words:
    description: 'The number of words to generate'
    required: false
    default: 3
  parts-of-speech:
    description:
      'The parts of speech to use. One of the following: noun, adjective. Note
      that, if provided, parts-of-speech must be a string with comma separated
      options of the same number as the number of words you are requesting.'
    required: false
    default: false

# Define your outputs here.
outputs:
  words-kebab:
    description: 'The generated words in kebab-case'
  words-camel:
    description: 'The generated words in camelCase'
  words-sentence:
    description: 'The generated words in sentence case'
  words-lower:
    description: 'The generated words in lower case'
  words-title:
    description: 'The generated words in title case'
  time:
    description: 'A timestamp of when the action was run'

runs:
  using: node20
  main: dist/index.js
